import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  Download,
  Printer,
  FileText,
  Filter,
  Search,
  DollarSign,
  Receipt,
  TrendingUp,
  Share2
} from 'lucide-react';
import { toast } from 'sonner';
import { exportData } from '@/utils/exportUtils';
import { shareData } from '@/utils/shareUtils';
import { 
  FORM_CONSTANTS,
  getCardClass,
  getInputClass,
  getLabelClass
} from '@/utils/formStyles';
import { useTransactions } from '@/contexts/TransactionsContext';
import { UnifiedPrintPreview } from '@/components/print/UnifiedPrintPreview';

interface ExpenseRegisterScreenProps {
  isDarkMode: boolean;
}

export function ExpenseRegisterScreen({ isDarkMode }: ExpenseRegisterScreenProps) {
  const { expenses, refreshExpenses } = useTransactions();

  React.useEffect(() => {
    refreshExpenses();
    const interval = setInterval(refreshExpenses, 60000);
    return () => clearInterval(interval);
  }, [refreshExpenses]);

  // Filter states
  const [dateFrom, setDateFrom] = useState('2024-02-01');
  const [dateTo, setDateTo] = useState('2024-02-29');
  const [categoryFilter, setCategoryFilter] = useState('');
  const [paymentModeFilter, setPaymentModeFilter] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [isPrintModalOpen, setIsPrintModalOpen] = useState(false);
  const [printData, setPrintData] = useState<any>(null);

  // Apply filters function
  const getFilteredExpenses = () => {
    return expenses.filter(expense => {
      const expenseDate = new Date(expense.expenseDate);
      const fromDate = new Date(dateFrom);
      const toDate = new Date(dateTo);
      
      const matchesDateRange = expenseDate >= fromDate && expenseDate <= toDate;
      const matchesCategory = !categoryFilter || expense.category.toLowerCase() === categoryFilter.toLowerCase();
      const matchesPaymentMode = !paymentModeFilter || expense.paymentMode.toLowerCase() === paymentModeFilter.toLowerCase();
      const matchesSearch = !searchQuery || 
        expense.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        expense.expenseNo.toLowerCase().includes(searchQuery.toLowerCase());
      
      return matchesDateRange && matchesCategory && matchesPaymentMode && matchesSearch;
    });
  };

  const filteredExpenses = getFilteredExpenses();

  const handleResetFilters = () => {
    setDateFrom('2024-02-01');
    setDateTo('2024-02-29');
    setCategoryFilter('');
    setPaymentModeFilter('');
    setSearchQuery('');
    toast.info('Filters reset successfully!');
  };

  const handleDownloadData = () => {
    if (filteredExpenses.length === 0) {
      toast.error('No data to export');
      return;
    }

    const dataToExport = filteredExpenses.map(e => ({
      'Expense No': e.expenseNo,
      'Date': new Date(e.expenseDate).toLocaleDateString('en-IN'),
      'Category': e.category,
      'Description': e.description,
      'Amount': e.amount,
      'Payment Mode': e.paymentMode,
      'Reference No': e.referenceNo || 'N/A'
    }));

    exportData(dataToExport, {
      fileName: `Expense-Register-${new Date().toISOString().split('T')[0]}`,
      format: 'xlsx'
    });
  };

  const handleShareDataLocal = async () => {
    if (filteredExpenses.length === 0) {
      toast.error('No data to share');
      return;
    }

    const summaryText = `Expense Register Report\nTotal Expenses: ${totals.count}\nTotal Amount: ₹${totals.totalAmount.toLocaleString()}`;
    
    await shareData({
      title: 'Expense Report',
      text: summaryText,
      url: window.location.href
    });
  };

  const handlePrint = () => {
    // Format data for ReportPrintView
    const formattedData = {
      reportNo: `EXP-${new Date().getTime().toString().slice(-6)}`,
      date: new Date().toLocaleDateString('en-IN'),
      headers: ['Expense No', 'Date', 'Category', 'Description', 'Amount', 'Mode'],
      keys: ['expenseNo', 'expenseDateDisplay', 'category', 'description', 'amount', 'paymentMode'],
      items: filteredExpenses.map(e => ({
        ...e,
        expenseDateDisplay: new Date(e.expenseDate).toLocaleDateString('en-IN')
      })),
      metaDetails: [
        { label: 'Period', value: `${new Date(dateFrom).toLocaleDateString('en-IN')} to ${new Date(dateTo).toLocaleDateString('en-IN')}` },
        { label: 'Category', value: categoryFilter || 'All' },
        { label: 'Payment Mode', value: paymentModeFilter || 'All' }
      ],
      summary: {
        totals: [
          { label: 'Total Expenses', value: totals.count.toString() },
          { label: 'Grand Total Amount', value: `₹${totals.totalAmount.toLocaleString()}`, isTotal: true }
        ],
        info: [
          { label: 'Generated By', content: 'Admin' },
          { label: 'Time', content: new Date().toLocaleTimeString() }
        ]
      }
    };
    
    setPrintData(formattedData);
    setIsPrintModalOpen(true);
  };

  const calculateTotals = () => {
    return {
      totalAmount: filteredExpenses.reduce((sum, item) => sum + item.amount, 0),
      count: filteredExpenses.length
    };
  };

  const totals = calculateTotals();

  const cardClass = getCardClass(isDarkMode);
  const inputClass = getInputClass(isDarkMode);
  const labelClass = getLabelClass(isDarkMode);

  return (
    <div className="p-6 space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className={`text-3xl font-bold mb-2 ${
            isDarkMode ? 'text-white' : 'text-gray-900'
          }`}>Expense Register</h1>
          <p className={`text-sm ${
            isDarkMode ? 'text-gray-400' : 'text-gray-600'
          }`}>Complete expense report with detailed breakdown</p>
        </div>
      </div>

      {/* Main Layout: Left Filter Panel + Right Report Table */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* LEFT: Filter Panel */}
        <div className="lg:col-span-3">
          <motion.div
            className={cardClass}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1 }}
          >
            <div className="p-6">
              <div className="flex items-center gap-2 mb-6">
                <Filter className={`w-5 h-5 ${isDarkMode ? 'text-blue-400' : 'text-blue-600'}`} />
                <h2 className={`text-lg font-bold ${
                  isDarkMode ? 'text-white' : 'text-gray-900'
                }`}>Filters</h2>
              </div>

              <div className="space-y-4">
                <div>
                  <label className={labelClass}>Date Range</label>
                  <div className="space-y-2">
                    <input 
                      type="date" 
                      className={inputClass}
                      value={dateFrom}
                      onChange={(e) => setDateFrom(e.target.value)}
                    />
                    <input 
                      type="date" 
                      className={inputClass}
                      value={dateTo}
                      onChange={(e) => setDateTo(e.target.value)}
                    />
                  </div>
                </div>

                <div>
                  <label className={labelClass}>Category</label>
                  <select className={inputClass} value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)}>
                    <option value="">All Categories</option>
                    <option value="utilities">Utilities</option>
                    <option value="rent">Rent</option>
                    <option value="supplies">Supplies</option>
                    <option value="maintenance">Maintenance</option>
                    <option value="transport">Transport</option>
                    <option value="salaries">Salaries</option>
                    <option value="marketing">Marketing</option>
                    <option value="insurance">Insurance</option>
                  </select>
                </div>

                <div>
                  <label className={labelClass}>Payment Mode</label>
                  <select className={inputClass} value={paymentModeFilter} onChange={(e) => setPaymentModeFilter(e.target.value)}>
                    <option value="">All Modes</option>
                    <option value="cash">Cash</option>
                    <option value="bank">Bank Transfer</option>
                    <option value="upi">UPI</option>
                    <option value="card">Card</option>
                  </select>
                </div>

                <div>
                  <label className={labelClass}>Search</label>
                  <div className="relative">
                    <Search className={`absolute left-3 top-3 w-4 h-4 ${
                      isDarkMode ? 'text-gray-400' : 'text-gray-500'
                    }`} />
                    <input 
                      type="text" 
                      placeholder="Search expenses..."
                      className={`${inputClass} pl-10`}
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                    />
                  </div>
                </div>

                <button 
                  className={`w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg transition-all ${
                    isDarkMode 
                      ? 'bg-gray-700 text-gray-300 hover:bg-gray-600' 
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                  onClick={handleResetFilters}
                >
                  Reset Filters
                </button>
              </div>
            </div>
          </motion.div>
        </div>

        {/* RIGHT: Report Table */}
        <div className="lg:col-span-9 space-y-4">
          {/* Summary Cards */}
          <div className="grid grid-cols-2 gap-4">
            <motion.div
              className={cardClass}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.15 }}
            >
              <div className="p-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-blue-500/20 flex items-center justify-center">
                    <Receipt className="w-5 h-5 text-blue-500" />
                  </div>
                  <div>
                    <p className={`text-xs ${
                      isDarkMode ? 'text-gray-400' : 'text-gray-600'
                    }`}>Total Expenses</p>
                    <p className={`text-xl font-bold ${
                      isDarkMode ? 'text-white' : 'text-gray-900'
                    }`}>{totals.count}</p>
                  </div>
                </div>
              </div>
            </motion.div>

            <motion.div
              className={cardClass}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
            >
              <div className="p-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-blue-600/20 flex items-center justify-center">
                    <DollarSign className="w-5 h-5 text-blue-600" />
                  </div>
                  <div>
                    <p className={`text-xs ${
                      isDarkMode ? 'text-gray-400' : 'text-gray-600'
                    }`}>Total Amount</p>
                    <p className={`text-xl font-bold ${
                      isDarkMode ? 'text-white' : 'text-gray-900'
                    }`}>₹{totals.totalAmount.toLocaleString()}</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Report Table */}
          <motion.div
            className={`${cardClass} flex flex-col overflow-hidden`}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <div className={`p-6 border-b ${isDarkMode ? 'border-gray-700' : 'border-gray-200'}`}>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className={`w-5 h-5 ${isDarkMode ? 'text-blue-400' : 'text-blue-600'}`} />
                  <h2 className={`text-lg font-bold ${
                    isDarkMode ? 'text-white' : 'text-gray-900'
                  }`}>Expense Report ({filteredExpenses.length})</h2>
                </div>
                <div className="flex items-center gap-3">
                  <button 
                    onClick={handleDownloadData}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-all text-sm font-medium ${
                    isDarkMode 
                      ? 'bg-blue-600/20 text-blue-400 hover:bg-blue-600/30' 
                      : 'bg-blue-50 text-blue-600 hover:bg-blue-100'
                  }`}>
                    <Download className="w-4 h-4" />
                    Download Data
                  </button>
                  <button 
                    onClick={handleShareDataLocal}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-all text-sm font-medium ${
                    isDarkMode 
                      ? 'bg-blue-700/20 text-blue-400 hover:bg-blue-700/30' 
                      : 'bg-blue-50 text-blue-700 hover:bg-blue-100'
                  }`}>
                    <Share2 className="w-4 h-4" />
                    Share Data
                  </button>
                  <button 
                    onClick={handlePrint}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-all text-sm font-medium ${
                    isDarkMode 
                      ? 'bg-blue-500/20 text-blue-400 hover:bg-blue-500/30' 
                      : 'bg-blue-50 text-blue-600 hover:bg-blue-100'
                  }`}>
                    <Printer className="w-4 h-4" />
                    Print
                  </button>
                </div>
              </div>
            </div>

            <div className="flex-1 overflow-auto">
              <div className="min-w-full inline-block align-middle">
                <table className="w-full table-fixed">
                  <colgroup>
                    <col style={{ width: '12%' }} />
                    <col style={{ width: '12%' }} />
                    <col style={{ width: '14%' }} />
                    <col style={{ width: '28%' }} />
                    <col style={{ width: '14%' }} />
                    <col style={{ width: '12%' }} />
                    <col style={{ width: '8%' }} />
                  </colgroup>
                  <thead className={`sticky top-0 ${isDarkMode ? 'bg-gray-800/95' : 'bg-gray-50/95'} backdrop-blur-sm z-10`}>
                    <tr className={`border-b ${isDarkMode ? 'border-gray-700' : 'border-gray-200'}`}>
                      <th className={`text-left py-3 px-3 text-xs font-semibold ${
                        isDarkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>Expense No</th>
                      <th className={`text-left py-3 px-3 text-xs font-semibold ${
                        isDarkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>Date</th>
                      <th className={`text-left py-3 px-3 text-xs font-semibold ${
                        isDarkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>Category</th>
                      <th className={`text-left py-3 px-3 text-xs font-semibold ${
                        isDarkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>Description</th>
                      <th className={`text-right py-3 px-3 text-xs font-semibold ${
                        isDarkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>Amount</th>
                      <th className={`text-center py-3 px-3 text-xs font-semibold ${
                        isDarkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>Payment Mode</th>
                      <th className={`text-center py-3 px-3 text-xs font-semibold ${
                        isDarkMode ? 'text-gray-400' : 'text-gray-600'
                      }`}>Status</th>
                    </tr>
                  </thead>
                  <tbody className={`divide-y ${isDarkMode ? 'divide-gray-700' : 'divide-gray-200'}`}>
                    {filteredExpenses.length === 0 ? (
                      <tr>
                        <td colSpan={7} className="text-center py-12">
                          <Receipt className={`w-12 h-12 mx-auto mb-4 ${isDarkMode ? 'text-gray-600' : 'text-gray-400'}`} />
                          <p className={`text-sm ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                            No expenses found for the selected filters
                          </p>
                        </td>
                      </tr>
                    ) : (
                      filteredExpenses.map((expense, index) => (
                        <motion.tr 
                          key={expense.id}
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          transition={{ delay: index * 0.02 }}
                          className={`transition-colors ${
                            isDarkMode ? 'hover:bg-gray-800/50' : 'hover:bg-gray-50'
                          }`}
                        >
                          <td className={`py-3 px-3 text-sm font-medium truncate ${
                            isDarkMode ? 'text-blue-400' : 'text-blue-600'
                          }`} title={expense.expenseNo}>
                            {expense.expenseNo}
                          </td>
                          <td className={`py-3 px-3 text-sm truncate ${
                            isDarkMode ? 'text-gray-300' : 'text-gray-700'
                          }`} title={expense.expenseDate}>
                            {new Date(expense.expenseDate).toLocaleDateString('en-IN')}
                          </td>
                          <td className={`py-3 px-3 text-sm truncate capitalize ${
                            isDarkMode ? 'text-gray-300' : 'text-gray-700'
                          }`} title={expense.category}>
                            {expense.category}
                          </td>
                          <td className={`py-3 px-3 text-sm truncate ${
                            isDarkMode ? 'text-white' : 'text-gray-900'
                          }`} title={expense.description}>
                            {expense.description}
                          </td>
                          <td className={`py-3 px-3 text-sm font-bold text-right truncate ${
                            isDarkMode ? 'text-blue-400' : 'text-blue-600'
                          }`} title={`₹${expense.amount.toLocaleString()}`}>
                            ₹{expense.amount.toLocaleString()}
                          </td>
                          <td className={`py-3 px-3 text-center`}>
                            <span className={`inline-flex items-center justify-center px-2 py-1 rounded-full text-xs font-medium capitalize ${
                              expense.paymentMode.toLowerCase() === 'cash'
                                ? 'bg-blue-400/20 text-blue-400'
                                : expense.paymentMode.toLowerCase() === 'bank'
                                ? 'bg-blue-500/20 text-blue-500'
                                : 'bg-blue-500/20 text-blue-500'
                            }`}>
                              {expense.paymentMode}
                            </span>
                          </td>
                          <td className={`py-3 px-3 text-center`}>
                            <span className={`inline-flex items-center justify-center px-2 py-1 rounded-full text-xs font-medium ${
                              expense.status === 'Paid'
                                ? 'bg-blue-600/20 text-blue-600'
                                : 'bg-blue-800/20 text-blue-800'
                            }`}>
                              {expense.status}
                            </span>
                          </td>
                        </motion.tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Summary Footer */}
            {filteredExpenses.length > 0 && (
              <div className={`p-6 border-t ${isDarkMode ? 'border-gray-700 bg-gray-800/50' : 'border-gray-200 bg-gray-50'}`}>
                <div className="flex items-center justify-between">
                  <div>
                    <p className={`text-xs font-medium ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                      Total Records Displayed
                    </p>
                    <p className={`text-xl font-bold mt-1 ${isDarkMode ? 'text-white' : 'text-gray-900'}`}>
                      {totals.count} Expenses
                    </p>
                  </div>
                  <div className="text-right">
                    <p className={`text-xs font-medium ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                      Grand Total
                    </p>
                    <p className={`text-2xl font-bold mt-1 ${isDarkMode ? 'text-blue-400' : 'text-blue-600'}`}>
                      ₹{totals.totalAmount.toLocaleString()}
                    </p>
                  </div>
                </div>
              </div>
            )}
          </motion.div>
        </div>
      </div>

      <UnifiedPrintPreview
        type="report"
        title="EXPENSE REGISTER REPORT"
        data={printData}
        isOpen={isPrintModalOpen}
        onClose={() => setIsPrintModalOpen(false)}
        isDarkMode={isDarkMode}
      />
    </div>
  );
}
