CREATE TABLE IF NOT EXISTS staff (
  id SERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  designation VARCHAR(120),
  mobile VARCHAR(30),
  email VARCHAR(150),
  joining_date DATE,
  salary NUMERIC(14,2) DEFAULT 0,
  address TEXT,
  bank_account VARCHAR(100),
  ifsc_code VARCHAR(30),
  status VARCHAR(20) DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobcards (
  id SERIAL PRIMARY KEY,
  jobcard_no VARCHAR(50) NOT NULL UNIQUE,
  customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
  customer_name VARCHAR(150) NOT NULL,
  phone VARCHAR(30),
  address TEXT,
  vehicle_id INTEGER REFERENCES vehicle_register(id) ON DELETE SET NULL,
  vehicle_no VARCHAR(30),
  vehicle_type VARCHAR(80),
  vehicle_make VARCHAR(120),
  vehicle_model VARCHAR(120),
  brand VARCHAR(120),
  model VARCHAR(120),
  transport_name VARCHAR(150),
  km_reading VARCHAR(50),
  service_type VARCHAR(120),
  work_type VARCHAR(120),
  technician_id INTEGER REFERENCES staff(id) ON DELETE SET NULL,
  technician_name VARCHAR(120),
  before_front_camber VARCHAR(50),
  before_front_caster VARCHAR(50),
  before_front_toe VARCHAR(50),
  before_rear_camber VARCHAR(50),
  before_rear_toe VARCHAR(50),
  after_front_camber VARCHAR(50),
  after_front_caster VARCHAR(50),
  after_front_toe VARCHAR(50),
  after_rear_camber VARCHAR(50),
  after_rear_toe VARCHAR(50),
  service_items JSONB DEFAULT '[]'::jsonb,
  complaint TEXT,
  work_done TEXT,
  remarks TEXT,
  status VARCHAR(30) DEFAULT 'pending',
  labour_charge NUMERIC(14,2) DEFAULT 0,
  parts_charge NUMERIC(14,2) DEFAULT 0,
  estimated_amount NUMERIC(14,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
